(function(){'use strict';
if(window.__TeslaLyricsPremium13)return;window.__TeslaLyricsPremium13=true;
var premiumState=null,premiumLyrics=null,stateAt=0,groups=[],translation=[],romaji=[],bpm=116,beatOffset=0,bars=[],base=[],lastFrame=0,lastPaint=0,lastPlayed=-1,idleTimer=null,coverFront='A',lastCover='',trackToken='',transitionTimer=null,seekHideTimer=null;
function q(id){return document.getElementById(id)}
if(!String.prototype.padStart){String.prototype.padStart=function(n,c){var z=String(c||' '),v=String(this);while(v.length<n)v=z+v;return v.slice(-n)}}
function fmt(ms){var n=Math.max(0,Math.floor((Number(ms)||0)/1000));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
function copy(x){var y={},k;for(k in x)if(Object.prototype.hasOwnProperty.call(x,k))y[k]=x[k];return y}
function keyOf(s){return [s&&s.title||'',s&&s.artist||'',s&&s.album||'',Number(s&&s.duration)||0].join('|')}
function mediaPos(){if(!premiumState)return 0;var p=Number(premiumState.elapsed)||0;if(premiumState.playing)p+=Math.max(0,Date.now()-stateAt);var d=Number(premiumState.duration)||0;if(d>0)p=Math.min(p,d);return Math.max(0,p)}
function seedInt(s){var h=2166136261>>>0;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rnd(x){x=(x^61)^(x>>>16);x=x+(x<<3);x=x^(x>>>4);x=Math.imul(x,0x27d4eb2d);x=x^(x>>>15);return (x>>>0)/4294967295}
function ensureUi(){var app=q('app'),aur=q('aurora');if(!app)return false;if(!q('premiumCoverA')){var a=document.createElement('div'),b=document.createElement('div');a.id='premiumCoverA';b.id='premiumCoverB';document.body.insertBefore(a,aur||document.body.firstChild);document.body.insertBefore(b,aur||document.body.firstChild)}var track=document.querySelector('header .track');if(track&&!q('premiumNowCard')){var card=document.createElement('div');card.id='premiumNowCard';var meta=document.createElement('div');meta.className='premiumMeta';while(track.firstChild)meta.appendChild(track.firstChild);track.appendChild(card);track.appendChild(meta)}if(!q('premiumStatus')){var old=q('status');if(old&&old.parentNode){var s=document.createElement('div');s.id='premiumStatus';s.innerHTML='<span id="premiumStatusDot"></span><span id="premiumStatusText">正在连接手机</span>';old.parentNode.appendChild(s)}}var active=document.querySelector('.line.active');if(active&&!q('premiumPhraseProgress')){var pp=document.createElement('div');pp.id='premiumPhraseProgress';active.appendChild(pp);var sub=document.createElement('div');sub.id='premiumSubline';active.appendChild(sub)}var p=q('progressWrap');if(p&&!q('premiumWave')){var w=document.createElement('div');w.id='premiumWave';p.appendChild(w);var n=document.createElement('span'),t=document.createElement('span'),bubble=document.createElement('div');n.id='premiumTimeNow';n.className='premiumTime';t.id='premiumTimeTotal';t.className='premiumTime';bubble.id='premiumSeekBubble';p.appendChild(n);p.appendChild(t);p.appendChild(bubble);for(var i=0;i<36;i++){var z=document.createElement('span');z.className='premiumWaveBar';w.appendChild(z);bars.push(z);base.push(.20+rnd(i*977+19)*.80)}}return true}
function reseed(s){var h=seedInt(keyOf(s));for(var i=0;i<base.length;i++){var x=i/Math.max(1,base.length-1),edge=.44+.56*Math.sin(Math.PI*x);base[i]=(.18+rnd(h+i*1103)*.82)*edge}lastPlayed=-1}
function parseRows(raw){var out=[],rows=String(raw||'').split(/\r?\n/);for(var i=0;i<rows.length;i++){var m=rows[i].match(/^\[(\d{1,3}):(\d{1,2}(?:\.\d{1,3})?)\]\s?(.*)$/);if(!m)continue;var text=(m[3]||'').replace(/<\d+:\d+(?:\.\d+)?>/g,'').trim();if(!text)continue;out.push({t:Math.round((parseInt(m[1],10)*60+parseFloat(m[2]))*1000),text:text})}out.sort(function(a,b){return a.t-b.t});return out}
function hasHan(s){return /[\u3400-\u9fff]/.test(s)}function hasKana(s){return /[\u3040-\u30ff]/.test(s)}function hasHangul(s){return /[\uac00-\ud7af]/.test(s)}function mostlyLatin(s){var a=String(s||'').replace(/[^A-Za-z]/g,'').length,b=String(s||'').replace(/\s/g,'').length;return b>0&&a/b>.48}
function grouped(raw){var rows=parseRows(raw),out=[],i,j;for(i=0;i<rows.length;){var g={t:rows[i].t,main:rows[i].text,translation:'',romaji:''},same=[rows[i].text];j=i+1;while(j<rows.length&&Math.abs(rows[j].t-rows[i].t)<=80){same.push(rows[j].text);j++}for(var k=1;k<same.length;k++){var ex=same[k],main=g.main;if((hasKana(main)||hasHangul(main)||mostlyLatin(main))&&hasHan(ex)){if(!g.translation)g.translation=ex;else if(!g.romaji)g.romaji=ex}else if((hasHan(main)||hasKana(main)||hasHangul(main))&&mostlyLatin(ex)){if(!g.romaji)g.romaji=ex;else if(!g.translation)g.translation=ex}else if(!g.translation)g.translation=ex}out.push(g);i=j}return out}
function nearest(arr,t){if(!arr||!arr.length)return'';var lo=0,hi=arr.length-1;while(lo<=hi){var m=(lo+hi)>>1;if(arr[m].t<t)lo=m+1;else hi=m-1}var a=arr[Math.max(0,Math.min(arr.length-1,lo))],b=arr[Math.max(0,Math.min(arr.length-1,lo-1))],x=Math.abs(a.t-t)<Math.abs(b.t-t)?a:b;return Math.abs(x.t-t)<=350?x.text:''}
function mergeExtras(){for(var i=0;i<groups.length;i++){if(!groups[i].translation)groups[i].translation=nearest(translation,groups[i].t);if(!groups[i].romaji)groups[i].romaji=nearest(romaji,groups[i].t)}}
function coreSafeLyrics(x){var y=copy(x),g=grouped(x&&x.lrc||''),lines=[];for(var i=0;i<g.length;i++){var ms=g[i].t,min=Math.floor(ms/60000),sec=((ms%60000)/1000).toFixed(3);if(sec.length<6)sec='0'+sec;lines.push('['+String(min).padStart(2,'0')+':'+sec+']'+g[i].main)}y.lrc=lines.join('\n');return y}
function activeIndex(pos){if(!groups.length||pos<groups[0].t)return-1;var lo=0,hi=groups.length-1;while(lo<=hi){var m=(lo+hi)>>1;if(groups[m].t<=pos)lo=m+1;else hi=m-1}return hi}
function lyricDelay(){var e=q('delayValue'),t=e?String(e.textContent||''):'';var m=t.match(/(延迟|提前)\s*([0-9.]+)s/);if(!m)return 1000;var v=Math.round(parseFloat(m[2])*1000);return m[1]==='提前'?-v:v}
function inferBpm(){if(premiumState&&Number(premiumState.bpm)>=50&&Number(premiumState.bpm)<=220)return Number(premiumState.bpm);if(groups.length<5)return 112;var gaps=[],i;for(i=1;i<groups.length&&gaps.length<48;i++){var g=groups[i].t-groups[i-1].t;if(g>=650&&g<=8500)gaps.push(g)}if(gaps.length<4)return 112;var best=112,bestErr=999;for(var x=74;x<=172;x+=2){var beat=60000/x,err=0,n=0;for(i=0;i<gaps.length;i++){var k=Math.max(1,Math.min(16,Math.round(gaps[i]/beat))),e=Math.abs(gaps[i]-k*beat)/beat;err+=Math.min(.55,e);n++}err/=Math.max(1,n);if(err<bestErr){bestErr=err;best=x}}return bestErr<.23?best:112}
function updateTempo(){bpm=inferBpm();var beat=60000/bpm;beatOffset=groups.length?(groups[0].t%beat):0}
function phraseProgress(pos){var lp=Math.max(0,pos-lyricDelay()),idx=activeIndex(lp);if(idx<0)return{idx:-1,r:0};var a=groups[idx].t,b=idx+1<groups.length?groups[idx+1].t:a+3600,r=Math.max(0,Math.min(1,(lp-a)/Math.max(650,b-a)));return{idx:idx,r:r}}
function paintPhrase(pos){var p=phraseProgress(pos),bar=q('premiumPhraseProgress'),sub=q('premiumSubline'),active=document.querySelector('.line.active');if(bar)bar.style.transform='scaleX('+(p.idx<0?0:p.r.toFixed(3))+')';if(active){active.style.opacity=String(.88+p.r*.12);var txt=active.querySelector('.txt'),len=txt?String(txt.textContent||'').replace(/\s/g,'').length:0;active.style.fontSize=len>31?'39px':len>24?'47px':''}if(!sub)return;if(p.idx<0||!groups[p.idx]){sub.className='';sub.innerHTML='';return}var g=groups[p.idx],parts=[];if(g.translation)parts.push('<span>'+escapeHtml(g.translation)+'</span>');if(g.romaji)parts.push('<span class="premiumRoman">'+escapeHtml(g.romaji)+'</span>');sub.innerHTML=parts.join('');sub.className=parts.length?'show':''}
function escapeHtml(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function frame(ts){if(ts-lastFrame<66){requestAnimationFrame(frame);return}lastFrame=ts;if(!bars.length)ensureUi();var pos=mediaPos(),dur=premiumState?Number(premiumState.duration)||0:0,ratio=dur>0?Math.max(0,Math.min(1,pos/dur)):0,played=Math.floor(ratio*bars.length),beat=60000/Math.max(60,bpm),phase=((pos-beatOffset)%beat+beat)%beat/beat,pulse=premiumState&&premiumState.playing?Math.exp(-phase*6.4):0,center=Math.floor(((pos/beat)%bars.length+bars.length)%bars.length);for(var i=0;i<bars.length;i++){var local=Math.max(0,1-Math.abs(i-center)/4),slow=.5+.5*Math.sin(pos/1000*1.18+i*.57),amp=.17+base[i]*.55+slow*.10+pulse*local*.30;if(!premiumState||!premiumState.playing)amp=.16+base[i]*.20;bars[i].style.transform='scaleY('+Math.max(.14,Math.min(1,amp)).toFixed(3)+')'}if(played!==lastPlayed){lastPlayed=played;for(i=0;i<bars.length;i++){bars[i].classList.toggle('played',i<played);bars[i].classList.toggle('current',i===played)}}var active=document.querySelector('.line.active');if(active&&premiumState&&premiumState.playing)active.style.transform='scale('+(1+pulse*.008).toFixed(4)+')';else if(active)active.style.transform='scale(1)';if(ts-lastPaint>110){lastPaint=ts;paintPhrase(pos);var n=q('premiumTimeNow'),t=q('premiumTimeTotal');if(n)n.textContent=fmt(pos);if(t)t.textContent=fmt(dur);renderStatus()}requestAnimationFrame(frame)}
function renderStatus(){var box=q('premiumStatus'),txt=q('premiumStatusText');if(!box||!txt)return;var fresh=premiumState&&Date.now()-stateAt<40000,label='正在连接手机',cls='';if(fresh){label='已连接';cls='ok'}else if(premiumState){label='恢复中';cls='warn'}txt.textContent=label;box.className=cls}
function hashTheme(k){var h=0;for(var i=0;i<k.length;i++)h=((h<<5)-h+k.charCodeAt(i))|0;h=Math.abs(h);document.documentElement.style.setProperty('--h1',String(h%360));document.documentElement.style.setProperty('--h2',String((h+61)%360));document.documentElement.style.setProperty('--h3',String((h+138)%360));document.documentElement.style.setProperty('--text-main','#fff')}
function rgbHue(r,g,b){r/=255;g/=255;b/=255;var mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn,h=0;if(d===0)h=0;else if(mx===r)h=60*(((g-b)/d)%6);else if(mx===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4);if(h<0)h+=360;return h}
function palette(img){try{var c=document.createElement('canvas');c.width=8;c.height=8;var ctx=c.getContext('2d');ctx.drawImage(img,0,0,8,8);var d=ctx.getImageData(0,0,8,8).data,best=[];for(var i=0;i<d.length;i+=4){var r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?((mx-mn)/mx):0,br=mx/255;if(sat<.17||br<.15||br>.96)continue;var h=rgbHue(r,g,b),sc=sat*(.4+.6*br),ok=true;for(var j=0;j<best.length;j++){var df=Math.abs(best[j].h-h);df=Math.min(df,360-df);if(df<24){if(sc>best[j].s)best[j]={h:h,s:sc};ok=false;break}}if(ok)best.push({h:h,s:sc});best.sort(function(a,b){return b.s-a.s});if(best.length>3)best.length=3}if(best.length){var h1=best[0].h,h2=best[1]?best[1].h:(h1+61)%360,h3=best[2]?best[2].h:(h1+138)%360;document.documentElement.style.setProperty('--h1',String(Math.round(h1)));document.documentElement.style.setProperty('--h2',String(Math.round(h2)));document.documentElement.style.setProperty('--h3',String(Math.round(h3)));document.documentElement.style.setProperty('--text-main',(h1>=15&&h1<=58)?'#fff8ee':'#fff')}}catch(e){}}
function cleanTitle(s){var x=String(s||'').trim();x=x.replace(/\s*[（(【\[][^）)】\]]*[）)】\]]\s*$/g,'').trim();return x||String(s||'').trim()}
function firstArtist(s){return String(s||'').split(/\s*(?:\/|、|,|，|×|;|；| feat\.? | ft\.? )\s*/i)[0]||''}
function compact(s){return String(s||'').toLowerCase().replace(/[\s\-—_·•.,，。!！?？:：'"“”‘’/\\]/g,'')}
function swapCover(url){var a=q('premiumCoverA'),b=q('premiumCoverB'),card=q('premiumNowCard');if(!a||!b)return;var next=coverFront==='A'?b:a,old=coverFront==='A'?a:b,img=new Image();try{img.crossOrigin='anonymous'}catch(e){}img.onload=function(){palette(img);next.style.backgroundImage='url("'+url.replace(/"/g,'')+'")';next.style.opacity='.61';next.style.transform='scale(1.095)';old.style.opacity='0';old.style.transform='scale(1.12)';if(card)card.style.backgroundImage='url("'+url.replace(/"/g,'')+'")';coverFront=coverFront==='A'?'B':'A';setTimeout(function(){if(old.style.opacity==='0')old.style.backgroundImage='none'},650)};img.src=url}
function lookupCover(s){var k=(s.title||'')+'|'+(s.artist||'');if(k===lastCover)return;lastCover=k;hashTheme(k);var term=(cleanTitle(s.title)+' '+firstArtist(s.artist)).trim();if(!term)return;function go(country,done){try{var x=new XMLHttpRequest();x.open('GET','https://itunes.apple.com/search?entity=song&limit=4&country='+country+'&term='+encodeURIComponent(term),true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status<200||x.status>=300){done(false);return}try{var j=JSON.parse(x.responseText);if(k!==lastCover){done(true);return}if(!j.results||!j.results.length){done(false);return}var pick=j.results[0];for(var i=0;i<j.results.length;i++)if(compact(j.results[i].trackName)===compact(cleanTitle(s.title))){pick=j.results[i];break}var art=String(pick.artworkUrl100||'').replace('100x100bb','300x300bb');if(art){swapCover(art);done(true);return}}catch(e){}done(false)};x.send()}catch(e){done(false)}}go('CA',function(ok){if(!ok)go('CN',function(){})})}
function transition(){clearTimeout(transitionTimer);document.body.classList.add('trackSwitch');transitionTimer=setTimeout(function(){document.body.classList.remove('trackSwitch')},360)}
function applyState(s){if(!s||s.kind!=='state')return;var k=keyOf(s),changed=k!==trackToken;premiumState=s;stateAt=Date.now();if(changed){trackToken=k;transition();reseed(s);lookupCover(s);document.body.classList.add('premiumNoLyrics')}var artist=q('artist');if(artist){var sub=s.artist||'';if(s.album)sub+=(sub?' · ':'')+s.album;artist.textContent=sub||s.source||'手机播放器'}document.body.classList.toggle('premiumPaused',!s.playing);updateTempo();renderStatus()}
function applyLyrics(x){if(!x||x.kind!=='lyrics')return;premiumLyrics=x;groups=grouped(x.lrc||'');translation=parseRows(x.translationLrc||x.translation||'');romaji=parseRows(x.romajiLrc||x.romaji||'');mergeExtras();document.body.classList.toggle('premiumNoLyrics',groups.length<4);updateTempo()}
function observeCoreCover(){var c=q('coverBg');if(!c||!window.MutationObserver)return;var last='';function sync(){var bg=c.style.backgroundImage||'';if(!bg||bg==='none'||bg===last)return;last=bg;var m=bg.match(/url\(["']?(.*?)["']?\)/);if(m&&m[1])swapCover(m[1])}var o=new MutationObserver(sync);o.observe(c,{attributes:true,attributeFilter:['style']});sync()}
function wrapHooks(){var os=window.tlxAcceptState,ol=window.tlxAcceptLyrics;window.tlxAcceptState=function(x){try{if(os)os(x)}finally{applyState(x)}};window.tlxAcceptLyrics=function(x){try{applyLyrics(x);if(ol)ol(coreSafeLyrics(x))}catch(e){if(ol)ol(x)}}}
function isInteractive(el){var n=el;while(n&&n!==document.body){var tag=String(n.tagName||'').toLowerCase();if(tag==='button'||tag==='a'||n.id==='progressWrap'||n.id==='controlDock')return true;n=n.parentNode}return false}
function wake(el){if(el&&isInteractive(el))return;document.body.classList.remove('premiumIdle');document.body.classList.remove('dockHidden');clearTimeout(idleTimer);idleTimer=setTimeout(function(){document.body.classList.add('premiumIdle')},4800)}
function seekBubble(x){var p=q('progressWrap'),b=q('premiumSeekBubble');if(!p||!b||!premiumState)return;var r=p.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(x-r.left)/r.width)),ms=ratio*(Number(premiumState.duration)||0);b.textContent=fmt(ms);b.style.left=(ratio*100).toFixed(2)+'%';b.className='show';clearTimeout(seekHideTimer);seekHideTimer=setTimeout(function(){b.className=''},900)}
function initNight(){var h=(new Date()).getHours();document.body.classList.toggle('premiumNight',h>=22||h<6)}
function boot(){if(!ensureUi()){setTimeout(boot,80);return}wrapHooks();observeCoreCover();initNight();wake();document.body.addEventListener('mousedown',function(e){wake(e.target)});document.body.addEventListener('touchstart',function(e){wake(e.target)},{passive:true});var p=q('progressWrap');if(p){p.addEventListener('mousemove',function(e){if(e.buttons)seekBubble(e.clientX)});p.addEventListener('mousedown',function(e){seekBubble(e.clientX)});p.addEventListener('touchstart',function(e){if(e.touches&&e.touches[0])seekBubble(e.touches[0].clientX)},{passive:true});p.addEventListener('touchmove',function(e){if(e.touches&&e.touches[0])seekBubble(e.touches[0].clientX)},{passive:true})}var close=q('dockClose');if(close)close.addEventListener('click',function(){clearTimeout(idleTimer);document.body.classList.add('premiumIdle')});requestAnimationFrame(frame)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
