(function(){'use strict';
if(window.__TeslaLyricsPremium11)return;window.__TeslaLyricsPremium11=true;
var premiumState=null,premiumLyrics=null,stateAt=0,lrcLines=[],bpm=116,beatOffset=0,bars=[],base=[],lastFrame=0,lastPaint=0,lastPlayed=-1,idleTimer=null,coverFront='A',lastCover='',lastTitle='',lastArtist='';
function q(id){return document.getElementById(id)}
function fmt(ms){var n=Math.max(0,Math.floor((Number(ms)||0)/1000));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')}
if(!String.prototype.padStart){String.prototype.padStart=function(n,c){var z=String(c||' '),v=String(this);while(v.length<n)v=z+v;return v.slice(-n)}}
function mediaPos(){if(!premiumState)return 0;var p=Number(premiumState.elapsed)||0;if(premiumState.playing)p+=Math.max(0,Date.now()-stateAt);var d=Number(premiumState.duration)||0;if(d>0)p=Math.min(p,d);return Math.max(0,p)}
function keyOf(s){return [s&&s.title||'',s&&s.artist||'',s&&s.album||'',Number(s&&s.duration)||0].join('|')}
function seedInt(s){var h=2166136261>>>0;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rnd(x){x=(x^61)^(x>>>16);x=x+(x<<3);x=x^(x>>>4);x=Math.imul(x,0x27d4eb2d);x=x^(x>>>15);return (x>>>0)/4294967295}
function ensureUi(){var app=q('app'),aur=q('aurora');if(!app)return false;if(!q('premiumCoverA')){var a=document.createElement('div'),b=document.createElement('div');a.id='premiumCoverA';b.id='premiumCoverB';document.body.insertBefore(a,aur||document.body.firstChild);document.body.insertBefore(b,aur||document.body.firstChild)}if(!q('premiumStatus')){var old=q('status');if(old&&old.parentNode){var s=document.createElement('div');s.id='premiumStatus';s.innerHTML='<span id="premiumStatusDot"></span><span id="premiumStatusText">正在连接手机</span>';old.parentNode.appendChild(s)}}var p=q('progressWrap');if(p&&!q('premiumWave')){var w=document.createElement('div');w.id='premiumWave';p.appendChild(w);var n=document.createElement('span'),t=document.createElement('span');n.id='premiumTimeNow';n.className='premiumTime';t.id='premiumTimeTotal';t.className='premiumTime';p.appendChild(n);p.appendChild(t);for(var i=0;i<28;i++){var z=document.createElement('span');z.className='premiumWaveBar';w.appendChild(z);bars.push(z);base.push(.25+rnd(i*977+19)*.75)}}return true}
function reseed(s){var h=seedInt(keyOf(s));for(var i=0;i<base.length;i++)base[i]=.22+rnd(h+i*1103)*.78;lastPlayed=-1}
function parseLrc(raw){var out=[],rows=String(raw||'').split(/\r?\n/);for(var i=0;i<rows.length;i++){var m=rows[i].match(/^\[(\d{1,3}):(\d{1,2}(?:\.\d{1,3})?)\]\s?(.*)$/);if(!m)continue;out.push({t:(parseInt(m[1],10)*60+parseFloat(m[2]))*1000,text:(m[3]||'').replace(/<\d+:\d+(?:\.\d+)?>/g,'').trim()})}out.sort(function(a,b){return a.t-b.t});return out}
function inferBpm(){if(premiumState&&Number(premiumState.bpm)>=50&&Number(premiumState.bpm)<=220)return Number(premiumState.bpm);if(lrcLines.length<5)return 116;var gaps=[],i;for(i=1;i<lrcLines.length&&gaps.length<48;i++){var g=lrcLines[i].t-lrcLines[i-1].t;if(g>=650&&g<=8500)gaps.push(g)}if(gaps.length<4)return 116;var best=116,bestErr=999;for(var x=76;x<=168;x+=2){var beat=60000/x,err=0,n=0;for(i=0;i<gaps.length;i++){var k=Math.max(1,Math.min(16,Math.round(gaps[i]/beat))),e=Math.abs(gaps[i]-k*beat)/beat;err+=Math.min(.55,e);n++}err/=Math.max(1,n);if(err<bestErr){bestErr=err;best=x}}return bestErr<.23?best:116}
function updateTempo(){bpm=inferBpm();var beat=60000/bpm;beatOffset=lrcLines.length?(lrcLines[0].t%beat):0}
function activeIndex(pos){if(!lrcLines.length||pos<lrcLines[0].t)return -1;var lo=0,hi=lrcLines.length-1;while(lo<=hi){var m=(lo+hi)>>1;if(lrcLines[m].t<=pos)lo=m+1;else hi=m-1}return hi}
function lyricDelay(){var e=q('delayValue'),t=e?String(e.textContent||''):'';var m=t.match(/(延迟|提前)\s*([0-9.]+)s/);if(!m)return 1000;var v=Math.round(parseFloat(m[2])*1000);return m[1]==='提前'?-v:v}
function paintKaraoke(pos){var lp=Math.max(0,pos-lyricDelay()),idx=activeIndex(lp),txt=document.querySelector('.line.active .txt');if(!txt||idx<0){if(txt){txt.style.backgroundImage='';txt.style.color=''}return}var a=lrcLines[idx].t,b=idx+1<lrcLines.length?lrcLines[idx+1].t:a+3500,r=Math.max(0,Math.min(1,(lp-a)/Math.max(600,b-a))),pct=(r*100).toFixed(1);txt.style.color='transparent';txt.style.backgroundImage='linear-gradient(90deg,#fff 0%,#fff '+pct+'%,rgba(255,255,255,.60) '+Math.min(100,Number(pct)+8)+'%,rgba(255,255,255,.50) 100%)'}
function frame(ts){if(ts-lastFrame<66){requestAnimationFrame(frame);return}lastFrame=ts;if(!bars.length)ensureUi();var pos=mediaPos(),dur=premiumState?Number(premiumState.duration)||0:0,ratio=dur>0?Math.max(0,Math.min(1,pos/dur)):0,played=Math.floor(ratio*bars.length),beat=60000/Math.max(60,bpm),phase=((pos-beatOffset)%beat+beat)%beat/beat,pulse=premiumState&&premiumState.playing?Math.exp(-phase*6.1):.05;for(var i=0;i<bars.length;i++){var slow=.5+.5*Math.sin(pos/1000*1.53+i*.67),amp=.23+base[i]*.43+slow*.16+pulse*(.18+base[i]*.16);if(!premiumState||!premiumState.playing)amp*=.72;bars[i].style.transform='scaleY('+Math.max(.18,Math.min(1,amp)).toFixed(3)+')'}if(played!==lastPlayed){lastPlayed=played;for(i=0;i<bars.length;i++){bars[i].classList.toggle('played',i<played);bars[i].classList.toggle('current',i===played)}}var active=document.querySelector('.line.active');if(active)active.style.transform=premiumState&&premiumState.playing?'scale('+(1+pulse*.010).toFixed(4)+')':'scale(1)';if(ts-lastPaint>120){lastPaint=ts;paintKaraoke(pos);var n=q('premiumTimeNow'),t=q('premiumTimeTotal');if(n)n.textContent=fmt(pos);if(t)t.textContent=fmt(dur);renderStatus()}requestAnimationFrame(frame)}
function renderStatus(){var box=q('premiumStatus'),txt=q('premiumStatusText');if(!box||!txt)return;var fresh=premiumState&&Date.now()-stateAt<40000,label='正在连接手机',cls='';if(fresh){label='已连接';cls='ok'}else if(premiumState){label='等待手机更新';cls='warn'}txt.textContent=label;box.className=cls}
function hashTheme(k){var h=0;for(var i=0;i<k.length;i++)h=((h<<5)-h+k.charCodeAt(i))|0;h=Math.abs(h);document.documentElement.style.setProperty('--h1',String(h%360));document.documentElement.style.setProperty('--h2',String((h+64)%360));document.documentElement.style.setProperty('--h3',String((h+142)%360))}
function rgbHue(r,g,b){r/=255;g/=255;b/=255;var mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn,h=0;if(d===0)h=0;else if(mx===r)h=60*(((g-b)/d)%6);else if(mx===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4);if(h<0)h+=360;return h}
function palette(img){try{var c=document.createElement('canvas');c.width=8;c.height=8;var ctx=c.getContext('2d');ctx.drawImage(img,0,0,8,8);var d=ctx.getImageData(0,0,8,8).data,best=[];for(var i=0;i<d.length;i+=4){var r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?((mx-mn)/mx):0,br=mx/255;if(sat<.18||br<.16||br>.96)continue;var h=rgbHue(r,g,b),sc=sat*(.45+.55*br),ok=true;for(var j=0;j<best.length;j++){var df=Math.abs(best[j].h-h);df=Math.min(df,360-df);if(df<24){if(sc>best[j].s)best[j]={h:h,s:sc};ok=false;break}}if(ok)best.push({h:h,s:sc});best.sort(function(a,b){return b.s-a.s});if(best.length>3)best.length=3}if(best.length){var h1=best[0].h,h2=best[1]?best[1].h:(h1+64)%360,h3=best[2]?best[2].h:(h1+142)%360;document.documentElement.style.setProperty('--h1',String(Math.round(h1)));document.documentElement.style.setProperty('--h2',String(Math.round(h2)));document.documentElement.style.setProperty('--h3',String(Math.round(h3)))}}catch(e){}}
function cleanTitle(s){var x=String(s||'').trim();x=x.replace(/\s*[（(【\[][^）)】\]]*[）)】\]]\s*$/g,'').trim();return x||String(s||'').trim()}
function firstArtist(s){return String(s||'').split(/\s*(?:\/|、|,|，|×|;|；| feat\.? | ft\.? )\s*/i)[0]||''}
function compact(s){return String(s||'').toLowerCase().replace(/[\s\-—_·•.,，。!！?？:：'"“”‘’/\\]/g,'')}
function swapCover(url){var a=q('premiumCoverA'),b=q('premiumCoverB');if(!a||!b)return;var next=coverFront==='A'?b:a,old=coverFront==='A'?a:b,img=new Image();try{img.crossOrigin='anonymous'}catch(e){}img.onload=function(){palette(img);next.style.backgroundImage='url("'+url.replace(/"/g,'')+'")';next.style.opacity='.63';old.style.opacity='0';coverFront=coverFront==='A'?'B':'A';setTimeout(function(){if(old.style.opacity==='0')old.style.backgroundImage='none'},620)};img.src=url}
function lookupCover(s){var k=(s.title||'')+'|'+(s.artist||'');if(k===lastCover)return;lastCover=k;hashTheme(k);var term=(cleanTitle(s.title)+' '+firstArtist(s.artist)).trim();if(!term)return;function go(country,done){try{var x=new XMLHttpRequest();x.open('GET','https://itunes.apple.com/search?entity=song&limit=4&country='+country+'&term='+encodeURIComponent(term),true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status<200||x.status>=300){done(false);return}try{var j=JSON.parse(x.responseText);if(k!==lastCover){done(true);return}if(!j.results||!j.results.length){done(false);return}var pick=j.results[0];for(var i=0;i<j.results.length;i++)if(compact(j.results[i].trackName)===compact(cleanTitle(s.title))){pick=j.results[i];break}var art=String(pick.artworkUrl100||'').replace('100x100bb','240x240bb');if(art){swapCover(art);done(true);return}}catch(e){}done(false)};x.send()}catch(e){done(false)}}go('CA',function(ok){if(!ok)go('CN',function(){})})}
function applyState(s){if(!s||s.kind!=='state')return;var changed=keyOf(s)!==keyOf(premiumState);premiumState=s;stateAt=Date.now();if(changed){reseed(s);lastTitle=s.title||'';lastArtist=s.artist||'';hashTheme((s.title||'')+'|'+(s.artist||''))}var artist=q('artist');if(artist){var sub=s.artist||'';if(s.album)sub+=(sub?' · ':'')+s.album;artist.textContent=sub||s.source||'手机播放器'}document.body.classList.toggle('premiumPaused',!s.playing);updateTempo();renderStatus()}
function applyLyrics(x){if(!x||x.kind!=='lyrics')return;premiumLyrics=x;lrcLines=parseLrc(x.lrc||'');updateTempo()}
function observeCoreCover(){var c=q('coverBg');if(!c||!window.MutationObserver)return;var last='';function sync(){var bg=c.style.backgroundImage||'';if(!bg||bg==='none'||bg===last)return;last=bg;var m=bg.match(/url\(["']?(.*?)["']?\)/);if(m&&m[1])swapCover(m[1])}var o=new MutationObserver(sync);o.observe(c,{attributes:true,attributeFilter:['style']});sync()}
function wrapHooks(){var os=window.tlxAcceptState,ol=window.tlxAcceptLyrics;window.tlxAcceptState=function(x){try{if(os)os(x)}finally{applyState(x)}};window.tlxAcceptLyrics=function(x){try{if(ol)ol(x)}finally{applyLyrics(x)}}}
function wake(){document.body.classList.remove('premiumIdle');clearTimeout(idleTimer);idleTimer=setTimeout(function(){document.body.classList.add('premiumIdle')},4600)}
function initNight(){var h=(new Date()).getHours();document.body.classList.toggle('premiumNight',h>=22||h<6)}
function boot(){if(!ensureUi()){setTimeout(boot,80);return}wrapHooks();observeCoreCover();initNight();wake();document.body.addEventListener('mousedown',function(e){if(!e.target||e.target.id!=='dockClose')wake()});document.body.addEventListener('touchstart',function(e){if(!e.target||e.target.id!=='dockClose')wake()},{passive:true});var close=q('dockClose'),open=q('dockOpen');if(close)close.addEventListener('click',function(){clearTimeout(idleTimer);document.body.classList.add('premiumIdle')});if(open)open.addEventListener('click',function(e){document.body.classList.remove('dockHidden');wake();if(e)e.stopPropagation()});requestAnimationFrame(frame)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();